### ISSUE TITLE
TypeError (using default settings)

### ISSUE THREAD

**Issue by dtchang** [jaesik817/Interaction-networks_tensorflow#4]
File "C:/AI/Code/- ORNet/IN jaesik817/interaction_network.py", line 154, in train
    total_idx=range(len(total_data));np.random.shuffle(total_idx);

  File "mtrand.pyx", line 4808, in mtrand.RandomState.shuffle (numpy\random\mtrand\mtrand.c:39350)

  File "mtrand.pyx", line 4811, in mtrand.RandomState.shuffle (numpy\random\mtrand\mtrand.c:39302)

TypeError: 'range' object does not support item assignment

**Comment by jsikyoon** [comment]
did you try with python3? 

when using range on python3, that can make problem as followed.

https://stackoverflow.com/questions/20484195/typeerror-range-object-does-not-support-item-assignment

**Comment by dtchang** [comment]
Yes. Can you update the code to work with python3 as well?

**Comment by dtchang** [comment]
Changed 
np.random.shuffle(..._idx);
to
np.random.shuffle(list(..._idx)); 
It worked for python3.

**Comment by jsikyoon** [comment]
sorry to late check this one T_T 

Except that part, the code is working fine on python3?

**Comment by dtchang** [comment]
Yes. The training completed and the videos generated. Thanks for implementing the project.

**Comment by jsikyoon** [comment]
welcome! then I will close this issue.
